### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by numazaki345** [numazaki345/chat-space#11]
#IPアドレス
18.179.139.8

**Comment by keisukekodama** [comment]
修正ありがとうございます！
再度確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

①ビューの崩れ

[![Image from Gyazo](https://i.gyazo.com/d9eb2a157e92bda3c7e184447e95e4f0.png)](https://gyazo.com/d9eb2a157e92bda3c7e184447e95e4f0)

お手本
[![Image from Gyazo](https://i.gyazo.com/93bed3341bbc09ce09f463b23b1bb838.png)](https://gyazo.com/93bed3341bbc09ce09f463b23b1bb838)

参考カリキュラム:https://master.tech-camp.in/curriculums/3944

②メッセージ送信後、メッセージ入力欄が空白にならない
[![Image from Gyazo](https://i.gyazo.com/4e3ab397f6451b7773dcdb8b093c35f9.gif)](https://gyazo.com/4e3ab397f6451b7773dcdb8b093c35f9)


修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by numazaki345** [comment]
修正しました

**Comment by miyu-yamamoto** [comment]
沼崎さん、修正ありがとうございます！
再度確認させて頂いたところ、①の余白は消えていたのですが
以下は修正の確認ができない状態です。

> **メッセージ送信後、メッセージ入力欄が空白にならない**

https://gyazo.com/c4e2441d0afe3653e633ae464183d501

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by numazaki345** [comment]
失礼しました
再度修正しましたので確認お願いします

**Comment by miyu-yamamoto** [comment]
沼崎さん、修正ありがとうございます！
確認したところメッセージ送信後、メッセージ入力欄にメッセージが残ってしまう現象が改善されておりました✨
ただ、新たに修正箇所がありますのでご確認をお願いします。

**○ 投稿されたメッセージがundefinedと表示されてしまう(自動更新の部分)**
https://gyazo.com/ee50f38addb239902c434fb40632cb87

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by numazaki345** [comment]
修正しました

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！修正お疲れさまでした！
